CREATE TABLE TB_SOCCER_TEAM (
  TST_ID           BIGINT(8) AUTO_INCREMENT PRIMARY KEY,
  TST_NAME         VARCHAR(50) NOT NULL,
  TST_DESCRIPTION  VARCHAR(50),
  TST_FOUNDED_IN   DATE NOT NULL,
  TST_LOCATED_IN   VARCHAR(50) NOT NULL,
  TST_COUNTRY      VARCHAR(20) NOT NULL,
  TST_IMAGE_URL    VARCHAR(200)
);